version: "3.8"

services:
  metube:
    container_name: metube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      - UID=1000
      - GID=1000
      - UMASK=022
      - DOWNLOAD_DIR=/downloads
      - STATE_DIR=/downloads/.metube
      - TEMP_DIR=/downloads
    command: ["./docker-entrypoint.sh"]
