services:
  metube:
    container_name: metube
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    restart: unless-stopped
    ports:
      - "8080:8081"
    volumes:
      - ./temp:/downloads
