services:
  metube:
    container_name: metube
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./temp:/downloads
